# Generated by Django 2.1.2 on 2018-11-28 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('fotoMascota', models.ImageField(upload_to='FotosMascotas/')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigoMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMensaje', models.CharField(max_length=30)),
                ('correoMensaje', models.EmailField(max_length=30)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=9)),
                ('region', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('tipoVivienda', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
