# Generated by Django 2.1.2 on 2018-11-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('fotoMascota', models.ImageField(upload_to='FotosMascotas/')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
    ]
