# Generated by Django 2.1.2 on 2018-11-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigoMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMensaje', models.CharField(max_length=30)),
                ('correoMensaje', models.EmailField(max_length=30)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
