# Generated by Django 2.1.2 on 2018-11-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
